spring:
  profiles:
    include: route # 从application-route.yml中引入路由配置
  application:
    name: gateway # Spring应用名
  # Nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

#Jwt配置
lyh:
  jwt:
    secret-key: 147qaz8522434d/*safjiweir47891!qwexuzigeuiib # 密钥
    expire-time: 36000000 # 过期时间（单位：毫秒）

server:
  port: 80